(() => {
  const dialog=document.querySelector('.dialog');
  const toast=m=>{const e=document.createElement('div');e.className='toast';e.setAttribute('role','status');e.textContent=m;document.body.append(e);setTimeout(()=>e.remove(),3600)};
  const views={
    today:['MOMENTO DE DECISÃO','Proteja 90 min para a decisão de expansão.','A agenda permite. A capacidade está adequada. O risco é a sequência de três reuniões sem intervalo antes do comitê.','Proteger janela 09:30–11:00','Ver evidências + alternativas',[['AGENDA','4h40','reuniões contínuas'],['PRIORIDADE','Alta','decisão de expansão'],['CONFIANÇA','84%','cobertura de sinal'],['RISCO','1','conflito evitável']]],
    agenda:['AGENDA DE CAPACIDADE','Recupere 2h20 de contexto antes de quinta.','Duas mudanças preservam a preparação para o conselho sem reduzir a cadência operacional: mover a revisão e converter um status em atualização assíncrona.','Simular agenda proposta','Comparar cenários',[['BLOCOS','2','de decisão recuperados'],['TROCAS','2','mudanças reversíveis'],['IMPACTO','2h20','contexto preservado'],['RISCO','Baixo','sem conflito crítico']]],
    decisions:['DECISION MEMORY','A expansão LATAM já tem uma decisão anterior parecida.','Em março, a preparação distribuída 48h antes reduziu reabertura de pauta. A memória não decide por você; ela devolve o contexto que a agenda apagou.','Abrir memória da decisão','Ver limites da evidência',[['CASOS','3','análogos encontrados'],['OUTCOME','1','resultado registrado'],['COBERTURA','Média','evidência incompleta'],['AÇÃO','Revisar','antes de reutilizar']]],
    intel:['INTELIGÊNCIA EXPLICÁVEL','O risco não é sua carga. É a sequência.','O sistema identifica continuidade de reuniões, proximidade da decisão e ausência de intervalo. Nenhum sinal clínico, inferência de humor ou julgamento individual é usado.','Inspecionar sinais usados','Ajustar fontes de dados',[['SINAIS','3','explicados'],['FONTES','2','consentidas'],['CONFIANÇA','84%','qualidade de cobertura'],['CONTROLE','Você','pode desligar']]],
    company:['ATLAS DE CAPACIDADE','Produto e Comercial disputam a mesma janela de decisão.','O padrão é agregado e só aparece em coorte mínima. A hipótese recomendada é uma quarta sem reuniões, simulada antes de qualquer política.','Simular intervenção','Abrir governança de dados',[['COORTE','18','participantes'],['FRICÇÃO','Alta','rituais excessivos'],['HIPÓTESE','1','a ser testada'],['VISIBILIDADE','Agregada','sem ranking individual']]]
  };
  const render=view=>{const [kicker,title,summary,primary,secondary,signals]=views[view];document.querySelector('#console-kicker').textContent=kicker;document.querySelector('#console-title').textContent=title;document.querySelector('#console-summary').textContent=summary;document.querySelector('#console-primary').textContent=primary;document.querySelector('#console-secondary').textContent=secondary;document.querySelector('#console-signals').innerHTML=signals.map(([label,value,detail])=>`<article><small>${label}</small><b>${value}</b><span>${detail}</span></article>`).join('');document.querySelectorAll('[data-view]').forEach(item=>item.classList.toggle('selected',item.dataset.view===view));};
  document.querySelectorAll('[data-view]').forEach(item=>item.addEventListener('click',()=>render(item.dataset.view)));
  document.querySelector('[data-action="story"]')?.addEventListener('click',()=>dialog.showModal());
  document.querySelectorAll('[data-action="close"]').forEach(e=>e.addEventListener('click',()=>dialog.close()));
  dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
  document.querySelector('#console-primary')?.addEventListener('click',()=>{const memory=document.querySelector('#ledger-card');if(!memory.dataset.proposal){memory.dataset.proposal='true';memory.insertAdjacentHTML('beforeend','<div class="new-record"><span class="dot good"></span><b>Janela de decisão</b><small>Proposta criada para revisão antes de alterar a agenda</small><em>aguardando confirmação</em></div>')}toast('Cenário V4: proposta criada e registrada na Decision Memory. A alteração de agenda exige sua confirmação.');document.querySelector('#ledger-card')?.scrollIntoView({behavior:'smooth',block:'center'});});
  document.querySelector('#console-secondary')?.addEventListener('click',()=>toast('Cenário V4: evidências e alternativas ficam visíveis antes de qualquer ação.'));
  document.querySelector('[data-action="policy"]')?.addEventListener('click',()=>toast('Cenário V4: política criada como experimento de coorte, sujeita a revisão antes de publicação.'));
})();
